
name: 'BJUT Clock In'

on:
  push:
  schedule:
    # 定时任务，在每天上午0点10分进行打卡
     - cron: '10 16 * * *'

jobs:
  clock:
    runs-on: ubuntu-latest
    steps:

      # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      # 执行仓库中的脚本文件
      - name: 'Clock In'
        run: python3 ./././bjut.py
